### ISSUE TITLE
\emph{} 效果为加下划线而不是斜体？

### ISSUE THREAD

**Issue by yanshengjia** [a367/seu-latex#1]
一般来说，给西文加 \emph{} 是将其变成斜体。

但在 seuthesis 中 \emph{} 命令的效果为给西文加下划线。

给中文加 \emph{} 似乎还会出现第一个字变成楷体其余字体不变还加下划线的情况。

那么在 seuthesis 中如何将文字变为 **斜体** 呢？

**Comment by piaozhx** [comment]
@yanshengjia 已修复这个问题，并增加相应示例

**Comment by yanshengjia** [comment]
666
