### ISSUE TITLE
bib 渲染问题：作者名字渲染错误

### ISSUE THREAD

**Issue by yanshengjia** [a367/seu-latex#3]
bib渲染后作者名字出现错误，第一作者和第二作者没问题，但是之后的作者只剩下了First Name 和 Last Name 的第一个字。

<img width="597" alt="2017-05-14 10 31 21" src="https://cloud.githubusercontent.com/assets/8682800/26030792/a451bb9c-3890-11e7-86cc-b2353cc02d57.png">

**Comment by piaozhx** [comment]
@yanshengjia 请贴上完整引用样式和Bib数据格式

**Comment by yanshengjia** [comment]
@inproceedings{tianxing2016,
  title={Entity Linking in Web Tables with Multiple Linked Knowledge Bases},
  author={Tianxing Wu, Shengjia Yan, Zhixin Piao, Liang Xu, Ruiming Wang, Guilin Qi},
  booktitle={Proceedings of the 6th Joint International Semantic Technology Conference (JIST 2016)},
  pages={249--263},
  year={2016}
}

**Comment by yanshengjia** [comment]
造成作者名字渲染错误的原因来自我在写 bibtex 的时候用逗号做了分隔符，实际上应该用 and。
