### ISSUE TITLE
参考文献格式

### ISSUE THREAD

**Issue by PiaoYeSEU** [a367/seu-latex#4]
常见的参考文献包括 学位论文，期刊，规范。
bib文件中的范例并不包括学位论文和期刊，网上常见的引用格式显示也不正确比如，引用学位论文@mastersthesis {test,
  author = {Piaoye},
  title = {GIS局部放在线监测},
  school = {东南大学},
  year = {2017},
}
则显示为
[1]Piaoye. GIS局部放在线监测[D]:[Master’s Thesis].[S.l.]:东南大学, 2017

明显有错误。所以如果可以的话请原作者在bib中添加正确的引用格式。

**Comment by piaozhx** [comment]
@PiaoYeSEU 你说的很对，参考文献格式之前忽视了，他有很多地方显示的结果都是有问题的，这个问题会抓紧修复。

**Comment by yanshengjia** [comment]
模板的Bibtex格式是支持 期刊 @ article 和 学位论文 @ masterthesis 的。

在写 bibtex 的应该用 and 作为分隔符，之前我用逗号做分隔符所以导致了参考文献中作者的格式问题。

**Comment by piaozhx** [comment]
@PiaoYeSEU 目前已经更新了参考文献部分，并加入了你给的测试样例。

**Comment by yanshengjia** [comment]
@a367 good job!

**Comment by PiaoYeSEU** [comment]
@a367 试过了，很完美，谢谢分享！

**Comment by PiaoYeSEU** [comment]
在使用测试样例中不包含的期刊时，好像不会显示期刊的[J]。如：


@ article{R1,
  author = {孙玉娇},
  title = {未来中国输电网发展模式的分析与展望},
  journal = {电网技术},
  year = {2013},
  pages = {1929-1935},
  volume = {7},
 % number = {1},
}
显示为[1]孙玉娇.未来中国输电网发展模式的分析与展望.电网技术, 2013, 7:1929–1935
正确的显示格式应该为：
[1]孙玉娇.未来中国输电网发展模式的分析与展望[J].电网技术, 2013, 7:1929–1935

**Comment by piaozhx** [comment]
@PiaoYeSEU 已经对你提到的问题做了修复并增加了对应的引用测试样例
