### ISSUE TITLE
图例的标注

### ISSUE THREAD

**Issue by PiaoYeSEU** [a367/seu-latex#6]
插入图片时，显示的图例为“图1.1GIS常见绝缘缺陷示意图 ”，而科技文献要求的格式为“图1-1 GIS常见绝缘缺陷示意图”。
代码如下：
\begin{figure}[!htbp]
  \centering
  \includegraphics[width=0.8\textwidth]{img/gis_fault.jpg}
  \hspace{1in}
  \caption{GIS常见绝缘缺陷示意图}
  \label{fig:gis_fault} %% label for entire figure
\end{figure}

博客http://blog.sina.com.cn/s/blog_5e16f1770100gdwr.html写出了修改图例的方法，但是似乎和模板不兼容。

**Comment by piaozhx** [comment]
@PiaoYeSEU 在《东南大学本科生毕业设计（论文）撰写规范 (试行）》第4页中，对图的要求为“**图序可以连续编序(如 图 15)，也可以逐章单独编序(如 图 2.5)，采用哪种方式应与表格、公式的编序方式统一，图序必须连续，不得重复 或跳跃。**”，不知道你为何你会出现这种要求。。。

**Comment by PiaoYeSEU** [comment]
我们学院比较奇葩（苦笑脸）
